[user_account]
username = "alice"
password = "alisPass"

[[instrument]]
site_id = "mace-head"
instrument="chm15k"
instrument_pid="blabla"
path_fmt = "/Users/alice/data/chm15k/%Y/file%Y%m%d-*.{nc,NC}"

[[instrument]]
site_id = "granada"
instrument="chm15k"
instrument_pid="blabla"
path_fmt = "/Users/alice/data/chm15k/%Y/file%Y%m%d-*.{nc,NC}"

[[model]]
site_id = "mace-head"
model="chm15k"
path_fmt = "/Users/alice/data/models/%Y/modelfile%Y%m%d-*.{nc,NC}"
