name: Publish to PyPI
on:
  push:
    tags:
      - v0.0.*

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Insall build and twine
        run: >-
          python -m
          pip install build twine --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build --sdist --wheel --outdir dist/ .
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: >-
          python -m
          twine upload dist/*
